# Generated by Django 6.1 on 2026-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.CharField(max_length=15, verbose_name='Дата оплаты'),
        ),
    ]
