# Generated by Django 6.1 on 2026-08-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_coursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Название курса'),
        ),
    ]
