# Generated by Django 6.1 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_coursepayment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
