# Generated by Django 6.1 on 2026-08-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_coursepayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='link',
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
